In [42]:
#Credits to Firnaz Ahamed https://medium.com/swlh/web-scraping-cricinfo-data-c134fce79a33

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import numpy as np

def extract_batting_data(series_id, match_id):

    URL = 'https://www.espncricinfo.com/series/'+ str(series_id) + '/scorecard/' + str(match_id)
    page = requests.get(URL)
    bs = BeautifulSoup(page.content, 'lxml')

    table_body=bs.find_all('tbody')
    batsmen_df = pd.DataFrame(columns=["Name","Desc","Runs", "Balls", "4s", "6s", "SR", "Team"])
    for i, table in enumerate(table_body[0:4:2]):
        rows = table.find_all('tr')
        for row in rows[::2]:
            cols=row.find_all('td')
            cols=[x.text.strip() for x in cols]
            if cols[0] == 'Extras':
                continue
            if len(cols) >= 8:
                batsmen_df = batsmen_df.append(pd.Series(
                [re.sub(r"\W+", ' ', cols[0].split("(c)")[0]).strip(), cols[1], 
                cols[2], cols[3], cols[5], cols[6], cols[7], i+1], 
                index=batsmen_df.columns ), ignore_index=True)
            else:
                batsmen_df = batsmen_df.append(pd.Series(
                [re.sub(r"\W+", ' ', cols[0].split("(c)")[0]).strip(), cols[1], 
                0, 0, 0, 0, 0, i+1], index = batsmen_df.columns), ignore_index=True)
                
    for i in range(2):
        dnb_row = bs.find_all("tfoot")[i].find_all("div")
        for c in dnb_row:
            dnb_cols = c.find_all('span')
            dnb = [x.text.strip().split("(c)")[0] for x in dnb_cols]
            dnb = filter(lambda item: item, [re.sub(r"\W+", ' ', x).strip() for x in dnb])
            for dnb_batsman in dnb:
                batsmen_df = batsmen_df.append(pd.Series([dnb_batsman, "DNB", 0, 0, 0, 0, 0, i+1], index = batsmen_df.columns), ignore_index =True)

    return batsmen_df

def extract_bowling_data(series_id, match_id):

    URL = 'https://www.espncricinfo.com/series/'+ str(series_id) + '/scorecard/' + str(match_id)
    page = requests.get(URL)
    bs = BeautifulSoup(page.content, 'lxml')

    table_body=bs.find_all('tbody')
    bowler_df = pd.DataFrame(columns=['Name', 'Overs', 'Maidens', 'Runs', 'Wickets',
                                      'Econ', 'Dots', '4s', '6s', 'Wd', 'Nb','Team'])
    for i, table in enumerate(table_body[1:4:2]):
        rows = table.find_all('tr')
        for row in rows:
            cols=row.find_all('td')
            cols=[x.text.strip() for x in cols]
            bowler_df = bowler_df.append(pd.Series([cols[0], cols[1], cols[2], cols[3], cols[4], cols[5], 
                                                    cols[6], cols[7], cols[8], cols[9], cols[10], (i==0)+1], 
                                                   index=bowler_df.columns ), ignore_index=True)
    return bowler_df

In [43]:
id_series = 8039 
id_match = 433606
batsmen_df = extract_batting_data(id_series, id_match)
bowler_df = extract_bowling_data(id_series, id_match)

In [44]:
batsmen_df

                Name                     Desc Runs Balls  4s 6s      SR Team
0        WU Tharanga          c Sehwag b Khan    2    20   0  0   10.00    1
1         TM Dilshan        b Harbhajan Singh   33    49   3  0   67.34    1
2      KC Sangakkara  c †Dhoni b Yuvraj Singh   48    67   5  0   71.64    1
3   DPMD Jayawardene                  not out  103    88  13  0  117.04    1
4     TT Samaraweera       lbw b Yuvraj Singh   21    34   2  0   61.76    1
5      CK Kapugedera           c Raina b Khan    1     5   0  0   20.00    1
6    KMDN Kulasekara         run out (†Dhoni)   32    30   1  1  106.66    1
7        NLTC Perera                  not out   22     9   3  1  244.44    1
8           V Sehwag            lbw b Malinga    0     2   0  0    0.00    2
9       SR Tendulkar  c †Sangakkara b Malinga   18    14   2  0  128.57    2
10         G Gambhir                 b Perera   97   122   9  0   79.50    2
11           V Kohli            c & b Dilshan   35    49   4  0   71.42    2
12          MS Dhoni                  not out   91    79   8  2  115.18    2
13      Yuvraj Singh                  not out   21    24   2  0   87.50    2
14        SL Malinga                      DNB    0     0   0  0       0    1
15          S Randiv                      DNB    0     0   0  0       0    1
16    M Muralitharan                      DNB    0     0   0  0       0    1
17          SK Raina                      DNB    0     0   0  0       0    2
18   Harbhajan Singh                      DNB    0     0   0  0       0    2
19            Z Khan                      DNB    0     0   0  0       0    2
20          MM Patel                      DNB    0     0   0  0       0    2
21       S Sreesanth                      DNB    0     0   0  0       0    2

In [45]:
bowler_df

               Name Overs Maidens Runs Wickets  Econ Dots 4s 6s Wd Nb Team
0            Z Khan    10       3   60       2  6.00   32  6  2  1  0    2
1       S Sreesanth     8       0   52       0  6.50   26  8  0  0  2    2
2          MM Patel     9       0   41       0  4.55   31  4  0  1  0    2
3   Harbhajan Singh    10       0   50       1  5.00   24  3  0  1  0    2
4      Yuvraj Singh    10       0   49       2  4.90   28  5  0  0  0    2
5      SR Tendulkar     2       0   12       0  6.00    4  0  0  3  0    2
6           V Kohli     1       0    6       0  6.00    3  1  0  0  0    2
7        SL Malinga     9       0   42       2  4.66   31  4  0  2  0    1
8   KMDN Kulasekara   8.2       0   64       0  7.68   20  8  1  0  0    1
9       NLTC Perera     9       0   55       1  6.11   27  5  1  2  0    1
10         S Randiv     9       0   43       0  4.77   24  3  0  0  0    1
11       TM Dilshan     5       0   27       1  5.40   14  2  0  1  0    1
12   M Muralitharan     8       0   39       0  4.87   23  3  0  1  0    1